export enum UsersActionTypeEnum {
    SET_USERS = 'SET_USERS',
    TOGGLE_FOLLOW = 'TOGGLE_FOLLOW',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
    SET_PAGES_AMOUNT = 'SET_PAGES_AMOUNT',
    SET_IS_LOADING = 'SET_IS_LOADING'
}